# Generated by Django 6.0.5 on 2026-06-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodApp', '0004_bloodrequest_accepted_by_bloodrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
